#docker pull harbor.skyline.lan/leaf-processor/leaf-processor:latest
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: leaf-deployment
#   labels:
#     app: leaf
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: leaf-processor
#   template:
#     metadata:
#       labels:
#         app: leaf-processor
#     spec:
#       containers:
#         - image: harbor.skyline.lan/leaf-processor/leaf-processor:latest
#           imagePullPolicy: Always
#           name: leaf-processor
#           ports:
#             - containerPort: 5000
#               protocol: TCP
#           resources:
#             limits:
#               memory: "8M"
#               cpu: "1000m"  #1000m = 1CPU   
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: leaf-processor
  name: leaf-processor
  namespace: default
spec:
  containers:
    - image: harbor.skyline.lan/leaf-processor/leaf-processor:latest
      imagePullPolicy: Always
      name: leaf-processor
      ports:
        - containerPort: 5000
          protocol: TCP
      resources: { }
      
---
apiVersion: v1
kind: Service
metadata:
  name: leaf-service
spec:
  selector:
    app: leaf-processor
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer


